// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmr3t021w7rUAmSOw7l0nu5UftYJzta9w',
    appId: '1:768808579408:web:2430d920e643429b7cfc55',
    messagingSenderId: '768808579408',
    projectId: 'blood-donors-app-7fe43',
    authDomain: 'blood-donors-app-7fe43.firebaseapp.com',
    storageBucket: 'blood-donors-app-7fe43.firebasestorage.app',
    measurementId: 'G-SEWGTNFGZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWe4dv7py-ugmYFz1BdjG3_oxqpzrNOo',
    appId: '1:768808579408:android:22c0b204d9445f5e7cfc55',
    messagingSenderId: '768808579408',
    projectId: 'blood-donors-app-7fe43',
    storageBucket: 'blood-donors-app-7fe43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxsuDVD0Bc1XB92A15_BVwV0RXy5CZas',
    appId: '1:768808579408:ios:d983eab4e08c7b787cfc55',
    messagingSenderId: '768808579408',
    projectId: 'blood-donors-app-7fe43',
    storageBucket: 'blood-donors-app-7fe43.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxsuDVD0Bc1XB92A15_BVwV0RXy5CZas',
    appId: '1:768808579408:ios:d983eab4e08c7b787cfc55',
    messagingSenderId: '768808579408',
    projectId: 'blood-donors-app-7fe43',
    storageBucket: 'blood-donors-app-7fe43.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmr3t021w7rUAmSOw7l0nu5UftYJzta9w',
    appId: '1:768808579408:web:ba75241ee7491d267cfc55',
    messagingSenderId: '768808579408',
    projectId: 'blood-donors-app-7fe43',
    authDomain: 'blood-donors-app-7fe43.firebaseapp.com',
    storageBucket: 'blood-donors-app-7fe43.firebasestorage.app',
    measurementId: 'G-P4V6GV6HY8',
  );
}
